--1
DECLARE
    count INT;
BEGIN
    SELECT COUNT(ID_PRODUKT) INTO count
                             FROM PRODUKT WHERE ID_KATEGORIA =
          (SELECT ID_KATEGORIA FROM KATEGORIA WHERE KATEGORIA = 'NABIAL');
    DBMS_OUTPUT.PUT_LINE('Ilosc produktów kategorii Nabial ' || count);
end;
--2
CREATE OR REPLACE TRIGGER ex2 BEFORE DELETE
    ON KATEGORIA
    BEGIN
            DBMS_OUTPUT.PUT_LINE('Exception');
    end;
--3
CREATE OR REPLACE PROCEDURE ex3(categoryName VARCHAR)
AS BEGIN
    IF (SELECT ID_KATEGORIA FROM KATEGORIA WHERE KATEGORIA=categoryName) IS NULL THEN
        INSERT INTO KATEGORIA VALUES ((SELECT MAX(ID_KATEGORIA) FROM KATEGORIA)+1, categoryName);
    end if;
    UPDATE PRODUKT SET ID_KATEGORIA=(SELECT KATEGORIA.ID_KATEGORIA FROM KATEGORIA WHERE KATEGORIA=categoryName)
    WHERE ID_KATEGORIA IS NULL;
end;