--1
DECLARE
    amount INT;
BEGIN
    SELECT COUNT(ID_PRODUKT)
    INTO amount
    FROM PRODUKT
    WHERE ID_KATEGORIA =
          (SELECT ID_KATEGORIA FROM KATEGORIA WHERE KATEGORIA = 'NABIAL');
    DBMS_OUTPUT.PUT_LINE('Ilosc produktów kategorii Nabial ' || amount);
end;
--2
CREATE OR REPLACE TRIGGER ex2
    BEFORE DELETE
    ON KATEGORIA
BEGIN
    raise_application_error('Delete on category');
end;
--3
CREATE OR REPLACE PROCEDURE ex3(categoryName VARCHAR)
AS
    number INT;
BEGIN
    SELECT COUNT(ID_KATEGORIA) INTO number FROM KATEGORIA WHERE KATEGORIA = categoryName;
    IF (number = 0) THEN
        INSERT INTO KATEGORIA VALUES ((SELECT MAX(ID_KATEGORIA) FROM KATEGORIA) + 1, categoryName);
    end if;
    UPDATE PRODUKT
    SET ID_KATEGORIA=(SELECT KATEGORIA.ID_KATEGORIA FROM KATEGORIA WHERE KATEGORIA = categoryName)
    WHERE ID_KATEGORIA IS NULL;
end;
--4
CREATE OR REPLACE TRIGGER ex4
    BEFORE UPDATE
    ON PRACOWNIK
    FOR EACH ROW
BEGIN
    IF :NEW.PENSJA < :OLD.PENSJA THEN
        :NEW.PENSJA := :OLD.PENSJA;
    end if;
end;
--5
CREATE OR REPLACE PROCEDURE ex5(cityName VARCHAR) AS
    number INT;
BEGIN
    SELECT COUNT(ID_MIASTO) INTO number FROM MIASTO WHERE MIASTO = cityName;
    IF number = 0 THEN
        DBMS_OUTPUT.PUT_LINE('City does not exist');
    ELSE
        UPDATE KLIENT
        SET ID_MIASTO = null
        WHERE ID_MIASTO = (SELECT ID_MIASTO FROM miasto WHERE MIASTO=cityName);
        DELETE FROM miasto WHERE MIASTO=cityName;
    END IF;
end;

BEGIN
    ex5('GDANSKA');
end;